/* Generated By:JJTree&JavaCC: Do not edit this line. CompilerConstants.java */
package compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANT = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int SOMA = 7;
  /** RegularExpression Id. */
  int SUBTRAI = 8;
  /** RegularExpression Id. */
  int MULTIPLICA = 9;
  /** RegularExpression Id. */
  int DIVIDE = 10;
  /** RegularExpression Id. */
  int POTENCIACAO = 11;
  /** RegularExpression Id. */
  int IGUALDADE = 12;
  /** RegularExpression Id. */
  int ATRIBUICAO = 13;
  /** RegularExpression Id. */
  int MENOR = 14;
  /** RegularExpression Id. */
  int MAIOR = 15;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 16;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 17;
  /** RegularExpression Id. */
  int ELOGICO = 18;
  /** RegularExpression Id. */
  int OULOGICO = 19;
  /** RegularExpression Id. */
  int TIPO_NUMERO = 20;
  /** RegularExpression Id. */
  int TIPO_TEXTO = 21;
  /** RegularExpression Id. */
  int TIPO_BOOL = 22;
  /** RegularExpression Id. */
  int TIPO_FUNCAO = 23;
  /** RegularExpression Id. */
  int ABRE_PARENTESE = 24;
  /** RegularExpression Id. */
  int FECHA_PARENTESE = 25;
  /** RegularExpression Id. */
  int ABRE_CHAVES = 26;
  /** RegularExpression Id. */
  int FECHA_CHAVES = 27;
  /** RegularExpression Id. */
  int PONTO_E_VIRGULA = 28;
  /** RegularExpression Id. */
  int VIRGULA = 29;
  /** RegularExpression Id. */
  int PONTO = 30;
  /** RegularExpression Id. */
  int ABRE_COLCHETES = 31;
  /** RegularExpression Id. */
  int FECHA_COLCHETES = 32;
  /** RegularExpression Id. */
  int INICIO_COMPILER = 33;
  /** RegularExpression Id. */
  int FIM_COMPILER = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"==\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"number\"",
    "\"string\"",
    "\"bool\"",
    "\"function\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"initialize\"",
    "\"terminate\"",
  };

}
