/* Generated By:JavaCC: Do not edit this line. CompilerTreeConstants.java Version 7.0.12 */
package compiler;

public interface CompilerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCOMPILER = 1;
  public int JJTBLOCO = 2;
  public int JJTID = 3;
  public int JJTDECLARACAVARIAVEIS = 4;
  public int JJTINICIOCOMPILER = 5;
  public int JJTFIMCOMPILER = 6;
  public int JJTNUMERO = 7;
  public int JJTTEXTO = 8;
  public int JJTBOOL = 9;
  public int JJTFUNCAO = 10;


  public String[] jjtNodeName = {
    "Start",
    "compiler",
    "bloco",
    "id",
    "declaracaVariaveis",
    "iniciocompiler",
    "fimcompiler",
    "numero",
    "texto",
    "bool",
    "funcao",
  };
}
/* JavaCC - OriginalChecksum=ae746bffc6178256f72dbc2504af0733 (do not edit this line) */
